<?php
require __DIR__ . '/bootstrap.php';

$method = $_SERVER['REQUEST_METHOD'];
ensure_teacher_role_enum($mysqli);
ensure_user_student_no_column($mysqli);
$jsonInput = get_json_input();
if ($method === 'POST') {
    $override = strtoupper(
        $_POST['_method'] ?? $_GET['_method'] ?? $jsonInput['_method'] ?? ($_SERVER['HTTP_X_HTTP_METHOD_OVERRIDE'] ?? '')
    );
    if (in_array($override, ['PATCH', 'PUT', 'DELETE'], true)) {
        $method = $override;
    }
}

switch ($method) {
    case 'GET':
        require_admin($mysqli);
        $result = $mysqli->query('SELECT id, username, display_name, role, student_no FROM users ORDER BY id ASC');
        if (!$result) {
            error_response('无法获取用户列表');
        }
        $users = [];
        while ($row = $result->fetch_assoc()) {
            $row['id'] = (int) $row['id'];
            $users[] = $row;
        }
        json_response(['users' => $users]);
        break;
    case 'POST':
        require_admin($mysqli);
        $input = $jsonInput ?: get_json_input();
        if (empty($input)) {
            $input = $_POST;
        }
        if (($input['action'] ?? '') === 'delete') {
            $userId = isset($input['id']) ? (int) $input['id'] : 0;
            if ($userId <= 0) {
                error_response('缺少用户ID');
            }
            if ($userId === (int) ($_SESSION['user']['id'] ?? 0)) {
                error_response('无法删除当前登录的管理员');
            }

            $stmt = $mysqli->prepare('SELECT role FROM users WHERE id = ? LIMIT 1');
            if (!$stmt) {
                error_response('无法查询用户信息');
            }
            $stmt->bind_param('i', $userId);
            $stmt->execute();
            $result = $stmt->get_result();
            $row = $result->fetch_assoc();
            $stmt->close();

            if (!$row) {
                error_response('用户不存在', 404);
            }

            if ($row['role'] === 'admin') {
                $countResult = $mysqli->query("SELECT COUNT(*) AS total FROM users WHERE role = 'admin'");
                if ($countResult) {
                    $countRow = $countResult->fetch_assoc();
                    if ((int) ($countRow['total'] ?? 0) <= 1) {
                        error_response('系统至少需要一名管理员');
                    }
                }
            }

            $stmt = $mysqli->prepare('DELETE FROM users WHERE id = ? LIMIT 1');
            if (!$stmt) {
                error_response('无法删除用户');
            }
            $stmt->bind_param('i', $userId);
            if (!$stmt->execute()) {
                $stmt->close();
                error_response('删除用户失败');
            }
            $stmt->close();
            json_response(['success' => true]);
        }
        $username = trim($input['username'] ?? '');
        $displayName = trim($input['display_name'] ?? '');
        $password = $input['password'] ?? '';
        $role = $input['role'] ?? 'student';
        $entryYear = normalize_entry_year($input['entry_year'] ?? '');
        $entryTerm = normalize_entry_term($input['entry_term'] ?? '');
        $rawStudentNo = $input['student_no'] ?? '';
        $requestedStudentNo = normalize_student_no($rawStudentNo);

        if ($username === '' || $password === '') {
            error_response('用户名和密码不能为空');
        }
        if ($rawStudentNo !== '' && $requestedStudentNo === '') {
            error_response('学号格式不正确，应为8位数字');
        }
        if (!in_array($role, ['student', 'admin', 'teacher'], true)) {
            $role = 'student';
        }

        $studentNo = null;
        $autoGenerated = false;
        if ($role === 'student') {
            if ($requestedStudentNo !== '') {
                $studentNo = $requestedStudentNo;
            } else {
                if ($entryYear === '' || $entryTerm === '') {
                    error_response('学员需要填写入库年份和期次以生成学号');
                }
                $studentNo = generate_student_no($mysqli, $entryYear, $entryTerm);
                if (!$studentNo) {
                    error_response('学号生成失败，请检查入库年份/期次或稍后重试');
                }
                $autoGenerated = true;
            }
        }
        $passwordHash = password_hash($password, PASSWORD_DEFAULT);

        $stmt = $mysqli->prepare('INSERT INTO users (username, display_name, role, password_hash, student_no) VALUES (?, ?, ?, ?, ?)');
        if (!$stmt) {
            error_response('无法创建用户');
        }
        $userId = null;
        $attempts = 0;
        $maxAttempts = 3;
        while ($attempts < $maxAttempts) {
            if ($autoGenerated && $attempts > 0) {
                $studentNo = generate_student_no($mysqli, $entryYear, $entryTerm);
                if (!$studentNo) {
                    $stmt->close();
                    error_response('学号生成失败，请稍后重试');
                }
            }
            $studentNoParam = $studentNo !== '' ? $studentNo : null;
            $stmt->bind_param('sssss', $username, $displayName, $role, $passwordHash, $studentNoParam);
            if ($stmt->execute()) {
                $userId = $stmt->insert_id;
                break;
            }
            if ($stmt->errno === 1062 && $autoGenerated) {
                $attempts++;
                continue;
            }
            $stmt->close();
            error_response('创建用户失败，可能用户名或学号已存在');
        }
        if (!$userId) {
            $stmt->close();
            error_response('学号生成冲突，请重试');
        }
        $stmt->close();

        json_response(['user' => ['id' => (int) $userId, 'username' => $username, 'display_name' => $displayName, 'role' => $role, 'student_no' => $studentNo]]);
        break;
    case 'PUT':
    case 'PATCH':
        $currentAdmin = require_admin($mysqli);
        $input = $jsonInput ?: get_json_input();
        $userId = isset($input['id']) ? (int) $input['id'] : 0;
        if ($userId <= 0) {
            error_response('缺少用户ID');
        }

        $stmt = $mysqli->prepare('SELECT id, username, role, student_no FROM users WHERE id = ? LIMIT 1');
        if (!$stmt) {
            error_response('无法查询用户信息');
        }
        $stmt->bind_param('i', $userId);
        $stmt->execute();
        $result = $stmt->get_result();
        $existing = $result->fetch_assoc();
        $stmt->close();

        if (!$existing) {
            error_response('用户不存在', 404);
        }

        $fields = [];
        $types = '';
        $values = [];

        if (array_key_exists('username', $input)) {
            $username = trim((string) ($input['username'] ?? ''));
            if ($username === '') {
                error_response('用户名不能为空');
            }
            $fields[] = 'username = ?';
            $types .= 's';
            $values[] = $username;
        }

        if (array_key_exists('display_name', $input)) {
            $displayName = trim((string) ($input['display_name'] ?? ''));
            if ($displayName === '') {
                $fields[] = 'display_name = NULL';
            } else {
                $fields[] = 'display_name = ?';
                $types .= 's';
                $values[] = $displayName;
            }
        }

        $finalRole = $existing['role'];
        if (array_key_exists('role', $input)) {
            $role = in_array($input['role'], ['admin', 'teacher'], true) ? $input['role'] : 'student';
            if ($existing['role'] === 'admin' && $role !== 'admin') {
                $countResult = $mysqli->query("SELECT COUNT(*) AS total FROM users WHERE role = 'admin'");
                if ($countResult) {
                    $countRow = $countResult->fetch_assoc();
                    if ((int) ($countRow['total'] ?? 0) <= 1) {
                        error_response('系统至少需要一名管理员');
                    }
                }
            }
            if ($userId === (int) $currentAdmin['id'] && $role !== 'admin') {
                error_response('无法修改当前登录管理员的角色');
            }
            $fields[] = 'role = ?';
            $types .= 's';
            $values[] = $role;
            $finalRole = $role;
        }

        $entryYear = normalize_entry_year($input['entry_year'] ?? '');
        $entryTerm = normalize_entry_term($input['entry_term'] ?? '');
        $rawStudentNo = $input['student_no'] ?? '';
        $requestedStudentNo = normalize_student_no($rawStudentNo);
        if ($rawStudentNo !== '' && $requestedStudentNo === '') {
            error_response('学号格式不正确，应为8位数字');
        }
        $wantsStudentNo = array_key_exists('student_no', $input) || $entryYear !== '' || $entryTerm !== '';
        if ($wantsStudentNo) {
            if ($finalRole !== 'student') {
                error_response('非学员无法设置学号');
            }
            if (!empty($existing['student_no'])) {
                error_response('学号已生成，不能修改');
            }
            if ($requestedStudentNo !== '') {
                $studentNo = $requestedStudentNo;
            } else {
                if ($entryYear === '' || $entryTerm === '') {
                    error_response('缺少入库年份或期次，无法生成学号');
                }
                $studentNo = generate_student_no($mysqli, $entryYear, $entryTerm);
                if (!$studentNo) {
                    error_response('学号生成失败，请检查入库年份/期次或稍后重试');
                }
            }
            $fields[] = 'student_no = ?';
            $types .= 's';
            $values[] = $studentNo;
        }

        if (!empty($input['password'])) {
            $password = (string) $input['password'];
            if (strlen($password) < 4) {
                error_response('新密码长度至少为4位');
            }
            $passwordHash = password_hash($password, PASSWORD_DEFAULT);
            $fields[] = 'password_hash = ?';
            $types .= 's';
            $values[] = $passwordHash;
        }

        if (!$fields) {
            error_response('没有可更新的字段');
        }

        $query = 'UPDATE users SET ' . implode(', ', $fields) . ' WHERE id = ? LIMIT 1';
        $stmt = $mysqli->prepare($query);
        if (!$stmt) {
            error_response('无法更新用户');
        }
        if ($types !== '') {
            $types .= 'i';
            $values[] = $userId;
            $stmt->bind_param($types, ...$values);
        } else {
            $stmt->bind_param('i', $userId);
        }

        if (!$stmt->execute()) {
            $stmt->close();
            error_response('更新用户信息失败，可能用户名已存在');
        }
        $stmt->close();

        $stmt = $mysqli->prepare('SELECT id, username, display_name, role, student_no FROM users WHERE id = ? LIMIT 1');
        if (!$stmt) {
            error_response('无法获取更新后的用户信息');
        }
        $stmt->bind_param('i', $userId);
        $stmt->execute();
        $result = $stmt->get_result();
        $user = $result->fetch_assoc();
        $stmt->close();

        if (!$user) {
            error_response('无法获取更新后的用户信息');
        }

        $user['id'] = (int) $user['id'];
        json_response(['user' => $user]);
        break;
    case 'DELETE':
        $currentAdmin = require_admin($mysqli);
        $input = $jsonInput ?: get_json_input();
        $userId = 0;
        if (!empty($input['id'])) {
            $userId = (int) $input['id'];
        } elseif (!empty($_GET['id'])) {
            $userId = (int) $_GET['id'];
        }
        if ($userId <= 0) {
            error_response('缺少用户ID');
        }
        if ($userId === (int) $currentAdmin['id']) {
            error_response('无法删除当前登录的管理员');
        }

        $stmt = $mysqli->prepare('SELECT role FROM users WHERE id = ? LIMIT 1');
        if (!$stmt) {
            error_response('无法查询用户信息');
        }
        $stmt->bind_param('i', $userId);
        $stmt->execute();
        $result = $stmt->get_result();
        $row = $result->fetch_assoc();
        $stmt->close();

        if (!$row) {
            error_response('用户不存在', 404);
        }

        if ($row['role'] === 'admin') {
            $countResult = $mysqli->query("SELECT COUNT(*) AS total FROM users WHERE role = 'admin'");
            if ($countResult) {
                $countRow = $countResult->fetch_assoc();
                if ((int) ($countRow['total'] ?? 0) <= 1) {
                    error_response('系统至少需要一名管理员');
                }
            }
        }

        $stmt = $mysqli->prepare('DELETE FROM users WHERE id = ? LIMIT 1');
        if (!$stmt) {
            error_response('无法删除用户');
        }
        $stmt->bind_param('i', $userId);
        if (!$stmt->execute()) {
            $stmt->close();
            error_response('删除用户失败');
        }
        $stmt->close();

        json_response(['deleted' => true]);
        break;
    default:
        error_response('不支持的请求方法', 405);
}
