<?php
require __DIR__ . '/bootstrap.php';
require_admin($mysqli);

ensure_cloud_files_table($mysqli); // no-op if exists, keep consistency
ensure_user_student_no_column($mysqli);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    error_response('只支持 POST 上传', 405);
}

if (empty($_FILES['file'])) {
    error_response('请上传包含用户数据的 CSV 文件');
}

$file = $_FILES['file'];
if ($file['error'] !== UPLOAD_ERR_OK) {
    error_response('上传失败，错误码: ' . $file['error']);
}

$maxSize = 5 * 1024 * 1024; // 5MB CSV
if ((int) $file['size'] > $maxSize) {
    error_response('文件过大，请控制在 5MB 以内');
}

$tmpPath = $file['tmp_name'];
$handle = fopen($tmpPath, 'rb');
if ($handle === false) {
    error_response('无法读取上传文件');
}

$header = fgetcsv($handle);
if ($header === false) {
    fclose($handle);
    error_response('文件为空或格式不正确');
}

$normalize = static function ($value) {
    $v = (string) $value;
    // Remove UTF-8 BOM if present
    $v = preg_replace('/^\xEF\xBB\xBF/', '', $v);
    return trim($v);
};

$expectedHeaders = ['username', 'display_name', 'password', 'role'];
$expectedHeadersWithEntry = ['username', 'display_name', 'password', 'role', 'entry_year', 'entry_term'];
$expectedHeadersWithStudentNo = ['username', 'display_name', 'password', 'role', 'student_no'];
$header = array_map($normalize, $header);
$lowerHeader = array_map('strtolower', $header);
$mode = '';
if ($lowerHeader === $expectedHeaders) {
    $mode = 'legacy';
} elseif ($lowerHeader === $expectedHeadersWithEntry) {
    $mode = 'entry';
} elseif ($lowerHeader === $expectedHeadersWithStudentNo) {
    $mode = 'student_no';
}
if ($mode === '') {
    fclose($handle);
    error_response('表头需为：username,display_name,password,role 或 username,display_name,password,role,entry_year,entry_term 或 username,display_name,password,role,student_no（CSV 格式）');
}

$insertStmt = $mysqli->prepare('INSERT INTO users (username, display_name, password_hash, role, student_no) VALUES (?, ?, ?, ?, ?)');
if (!$insertStmt) {
    fclose($handle);
    error_response('无法准备写入用户');
}

$inserted = 0;
$skipped = 0;
$errors = [];
$rowNumber = 1; // header counted
$sequenceCache = [];
$fetchNextStudentNo = function (string $entryYear, string $entryTerm) use ($mysqli, &$sequenceCache): ?string {
    $prefix = $entryYear . $entryTerm;
    if (strlen($prefix) !== 4) {
        return null;
    }
    if (!array_key_exists($prefix, $sequenceCache)) {
        $like = $prefix . '%';
        $stmt = $mysqli->prepare('SELECT student_no FROM users WHERE student_no LIKE ? ORDER BY student_no DESC LIMIT 1');
        if (!$stmt) {
            return null;
        }
        $stmt->bind_param('s', $like);
        $stmt->execute();
        $result = $stmt->get_result();
        $row = $result ? $result->fetch_assoc() : null;
        $stmt->close();
        $sequenceCache[$prefix] = 0;
        if ($row && !empty($row['student_no']) && strlen($row['student_no']) === 8) {
            $sequenceCache[$prefix] = (int) substr($row['student_no'], -4);
        }
    }
    $sequenceCache[$prefix]++;
    if ($sequenceCache[$prefix] > 9999) {
        return null;
    }
    return $prefix . str_pad((string) $sequenceCache[$prefix], 4, '0', STR_PAD_LEFT);
};

while (($row = fgetcsv($handle)) !== false) {
    $rowNumber++;
    // Skip empty lines
    if (count(array_filter($row, fn($v) => trim((string) $v) !== '')) === 0) {
        continue;
    }
    $row = array_map($normalize, $row);
    $username = '';
    $displayName = '';
    $password = '';
    $role = '';
    $entryYearRaw = '';
    $entryTermRaw = '';
    $studentNoRaw = '';
    if ($mode === 'legacy') {
        [$username, $displayName, $password, $role] = array_pad($row, 4, '');
    } elseif ($mode === 'entry') {
        [$username, $displayName, $password, $role, $entryYearRaw, $entryTermRaw] = array_pad($row, 6, '');
    } elseif ($mode === 'student_no') {
        [$username, $displayName, $password, $role, $studentNoRaw] = array_pad($row, 5, '');
    }

    if ($username === '' || $password === '') {
        $errors[] = "第 {$rowNumber} 行缺少用户名或密码，已跳过";
        $skipped++;
        continue;
    }
    if (!in_array($role, ['student', 'admin', 'teacher'], true)) {
        $errors[] = "第 {$rowNumber} 行角色无效（仅支持 student/admin/teacher），已按 student 处理";
        $role = 'student';
    }

    $passwordHash = password_hash($password, PASSWORD_DEFAULT);
    $studentNo = null;
    $autoGenerated = false;
    if ($role === 'student') {
        if ($mode === 'student_no') {
            $studentNo = normalize_student_no($studentNoRaw);
            if ($studentNo === '') {
                $errors[] = "第 {$rowNumber} 行学号无效，已跳过";
                $skipped++;
                continue;
            }
        } elseif ($mode === 'entry') {
            $entryYear = normalize_entry_year($entryYearRaw);
            $entryTerm = normalize_entry_term($entryTermRaw);
            if ($entryYear === '' || $entryTerm === '') {
                $errors[] = "第 {$rowNumber} 行缺少入库年份/期次，已跳过";
                $skipped++;
                continue;
            }
            $studentNo = $fetchNextStudentNo($entryYear, $entryTerm);
            if (!$studentNo) {
                $errors[] = "第 {$rowNumber} 行学号生成失败，已跳过";
                $skipped++;
                continue;
            }
            $autoGenerated = true;
        } else {
            $errors[] = "第 {$rowNumber} 行学员缺少入库信息（entry_year/entry_term），已跳过";
            $skipped++;
            continue;
        }
    }

    $attempts = 0;
    $maxAttempts = 3;
    $insertedRow = false;
    while ($attempts < $maxAttempts) {
        if ($autoGenerated && $attempts > 0) {
            $entryYear = normalize_entry_year($entryYearRaw);
            $entryTerm = normalize_entry_term($entryTermRaw);
            $studentNo = $fetchNextStudentNo($entryYear, $entryTerm);
            if (!$studentNo) {
                break;
            }
        }
        $studentNoParam = $studentNo !== '' ? $studentNo : null;
        $insertStmt->bind_param('sssss', $username, $displayName, $passwordHash, $role, $studentNoParam);
        if ($insertStmt->execute()) {
            $insertedRow = true;
            break;
        }
        if ($insertStmt->errno === 1062 && $autoGenerated) {
            $attempts++;
            continue;
        }
        break;
    }

    if ($insertedRow) {
        $inserted++;
        continue;
    }

    if ($insertStmt->errno === 1062) {
        $errors[] = "第 {$rowNumber} 行用户名或学号已存在，已跳过";
    } else {
        $errors[] = "第 {$rowNumber} 行写入失败：" . $insertStmt->error;
    }
    $skipped++;
}

fclose($handle);
$insertStmt->close();

json_response([
    'success' => true,
    'inserted' => $inserted,
    'skipped' => $skipped,
    'errors' => $errors
]);
